### ISSUE TITLE
Looking forward to get involved and contribute to the community 🎉

### ISSUE THREAD

**Issue by vedant-kakde** [SidHacksCommunity/support#1]
### First Name

Vedant

### Last Name

Kakde

### Discord Username (if applicable)

Vedant Kakde#9953

### Let us understand your motive.

I have been following Siddharth even before the community was built. I'm glad to be part of this amazing community. Excited for the upcoming community activities & events. I will contribute to the community in the best way possible from my side. For me it's all about learning and growing together.

**Comment by siddharthdayalwal** [comment]
![](https://media.giphy.com/media/LrY6OiICHS1TWZpGkf/giphy.gif)

Hey @vedant-kakde  👋🏻 

Thanks for requesting an invite! Welcome to SidHacks Community 🎉 

Before going ahead, I would want you to complete the below To-Do list.

## Your To-Do List ✔️ 
`You can click on the checkboxes as you complete them`
- [ ] Accept the invitation sent to you via mail.
- [ ] Change the appearance of this organization to "Public" from the people list [here](https://github.com/orgs/SidHacksCommunity/people/).
- [ ] Join our Discord Server [here](https://discord.gg/gPyR9Q9n8M).
  - [ ] Accept the Rules from `#📓〡rules` channel.
  - [ ] Introduce yourself to our community in `👋〡introduction` channel.
- [ ] Feel free to share your excitement on socials with `#SidHacksCommunity`. You can also tag me `@siddharth_hacks`.

- - -

Looking forward to interacting with you in our community! Welcome once again! 🤓

**Comment by vedant-kakde** [comment]
Trial
- [ ] #739
- [ ] https://github.com/octo-org/octo-repo/issues/740
- [ ] Add delight to the experience when all tasks are complete :tada:
