### ISSUE TITLE
Looking forward to get involved and contribute to the community 🎉

### ISSUE THREAD

**Issue by verma-kunal** [SidHacksCommunity/support#13]
### First Name

Kunal 

### Last Name

Verma

### Discord Username (if applicable)

Kunal#5142

### Let us understand your motive.

Hey Siddharth, it feels really awesome to see the community grow & being a part of it, along this journey. Since the launch of SidHacks community, its been really great to be able to interact with you & all the fellow folks we have here!
Looking forward to helping the community in whichever way i can & contribute to the cause of learning & empowering others 🙂

**Comment by siddharthdayalwal** [comment]
![](https://media.giphy.com/media/LrY6OiICHS1TWZpGkf/giphy.gif)

Hey @verma-kunal 👋🏻 

Thanks for requesting an invite! Welcome to SidHacks Community 🎉 

Before going ahead, I would want you to complete the below To-Do list.

## Your To-Do List ✔️ 

- Accept the invitation sent to you via mail.
- Change the appearance of this organization to "Public" from the people list [here](https://github.com/orgs/SidHacksCommunity/people/).
- Join our Discord Server [here](https://discord.gg/gPyR9Q9n8M).
  - Accept the Rules from `#📓〡rules` channel.
  - Introduce yourself to our community in `👋〡introduction` channel.
- Feel free to share your excitement on socials with `#SidHacksCommunity`. You can also tag me `@siddharth_hacks`.

__Close this issue once you complete all the above points.__
- - -

Looking forward to interacting with you in our community! Welcome once again! 🤓

**Comment by verma-kunal** [comment]
Yep, done all these !! 🙂
