### ISSUE TITLE
Looking forward to get involved and contribute to the community 🎉

### ISSUE THREAD

**Issue by vinzvinci** [SidHacksCommunity/support#3]
### First Name

Vincent

### Last Name

Villafuerte

### Discord Username (if applicable)

vinzvinci#5227

### Let us understand your motive.

Siddhart invited me to join SidHacks. I'm very interested to join in this community to collaborate and have fun with other members. I like to help the GitHub organization coz I'm an open-sourcerer.

**Comment by siddharthdayalwal** [comment]
![](https://media.giphy.com/media/LrY6OiICHS1TWZpGkf/giphy.gif)

Hey @vinzvinci 👋🏻 

Thanks for requesting an invite! Welcome to SidHacks Community 🎉 

Before going ahead, I would want you to complete the below To-Do list.

## Your To-Do List ✔️ 
`You can click on the checkboxes as you complete them`
- [ ] Accept the invitation sent to you via mail.
- [ ] Change the appearance of this organization to "Public" from the people list [here](https://github.com/orgs/SidHacksCommunity/people/).
- [ ] Join our Discord Server [here](https://discord.gg/gPyR9Q9n8M).
  - [ ] Accept the Rules from `#📓〡rules` channel.
  - [ ] Introduce yourself to our community in `👋〡introduction` channel.
- [ ] Feel free to share your excitement on socials with `#SidHacksCommunity`. You can also tag me `@siddharth_hacks`.

- - -

Looking forward to interacting with you in our community! Welcome once again! 🤓

**Comment by vinzvinci** [comment]
Done! Thank you :)
