### ISSUE TITLE
Looking forward to get involved and contribute to the community 🎉

### ISSUE THREAD

**Issue by aman34503** [SidHacksCommunity/support#30]
### First Name

Aman 

### Last Name

Shrivastava

### Discord Username (if applicable)

aman#4627

### Let us understand your motive.

I came to know about SidHacks through Siddharth himself from Your Linkedin , and I want to join the community so I can meet new people and learn from them, also wanna give back to communities and will try my best to help in any way possible. 
I can contribute to the community by staying active and keeping the engagement in the community to a maximum!
btw i am here to learn new techs

**Comment by siddharthdayalwal** [comment]
![](https://media.giphy.com/media/LrY6OiICHS1TWZpGkf/giphy.gif)

Hey @aman34503 👋🏻 

Thanks for requesting an invite! Welcome to SidHacks Community 🎉 

Before going ahead, I would want you to complete the below To-Do list.

## Your To-Do List ✔️ 

- Accept the invitation sent to you via mail.
- Change the appearance of this organization to "Public" from the people list [here](https://github.com/orgs/SidHacksCommunity/people/).
- Join our Discord Server [here](https://discord.gg/gPyR9Q9n8M).
  - Accept the Rules from `#📓〡rules` channel.
  - Introduce yourself to our community in `👋〡introduction` channel.
- Feel free to share your excitement on socials with `#SidHacksCommunity`. You can also tag me `@siddharth_hacks`.

__Close this issue once you complete all the above points.__
- - -

Looking forward to interacting with you in our community! Welcome once again! 🤓
