### ISSUE TITLE
Looking forward to get involved and contribute to the community 🎉

### ISSUE THREAD

**Issue by rockingrohit9639** [SidHacksCommunity/support#40]
### First Name

Rohit

### Last Name

Saini

### Discord Username (if applicable)

Rohit Saini#1017

### Let us understand your motive.

Hey there,
I am Rohit and I am Open Source enthusiast. And I think this community will help me for the same. So, I would love to contribute to this community.

**Comment by siddharthdayalwal** [comment]
![](https://media.giphy.com/media/LrY6OiICHS1TWZpGkf/giphy.gif)

Hey @rockingrohit9639 👋🏻 

Thanks for requesting an invite! Welcome to SidHacks Community 🎉 

Before going ahead, I would want you to complete the below To-Do list.

## Your To-Do List ✔️ 

- Accept the invitation sent to you via mail.
- Change the appearance of this organization to "Public" from the people list [here](https://github.com/orgs/SidHacksCommunity/people/).
- Join our Discord Server [here](https://discord.gg/gPyR9Q9n8M).
  - Accept the Rules from `#📓〡rules` channel.
  - Introduce yourself to our community in `👋〡introduction` channel.
- Feel free to share your excitement on socials with `#SidHacksCommunity`. You can also tag me `@siddharth_hacks`.

__Close this issue once you complete all the above points.__
- - -

Looking forward to interacting with you in our community! Welcome once again! 🤓

**Comment by rockingrohit9639** [comment]
> ![](https://camo.githubusercontent.com/ba949d9c47088b7f922c0250a04ff9cba5e5e31bb8fe86bd9e5f36906873180c/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4c7259364f69494348533154575a70476b662f67697068792e676966)
> 
> Hey @rockingrohit9639 👋🏻
> 
> Thanks for requesting an invite! Welcome to SidHacks Community 🎉
> 
> Before going ahead, I would want you to complete the below To-Do list.
> 
> ## Your To-Do List ✔️
> * Accept the invitation sent to you via mail.
> * Change the appearance of this organization to "Public" from the people list [here](https://github.com/orgs/SidHacksCommunity/people/).
> * Join our Discord Server [here](https://discord.gg/gPyR9Q9n8M).
>   
>   * Accept the Rules from `#📓〡rules` channel.
>   * Introduce yourself to our community in `👋〡introduction` channel.
> * Feel free to share your excitement on socials with `#SidHacksCommunity`. You can also tag me `@siddharth_hacks`.
> 
> **Close this issue once you complete all the above points.**
> 
> Looking forward to interacting with you in our community! Welcome once again! 🤓

Completed this todo-list. Thank you.
