### ISSUE TITLE
Looking forward to get involved and contribute to the community 🎉

### ISSUE THREAD

**Issue by Chanchal1603** [SidHacksCommunity/support#42]
### First Name

Chanchal

### Last Name

Bansal

### Discord Username (if applicable)

Chanchal#3379

### Let us understand your motive.

Hey there,
I am Chanchal and I am Open Source contributor. And I think this community will help me to make more amazing contributions. So, I would love to be a part of this community.

**Comment by siddharthdayalwal** [comment]
![](https://media.giphy.com/media/LrY6OiICHS1TWZpGkf/giphy.gif)

Hey @Chanchal1603 👋🏻 

Thanks for requesting an invite! Welcome to SidHacks Community 🎉 

Before going ahead, I would want you to complete the below To-Do list.

## Your To-Do List ✔️ 

- Accept the invitation sent to you via mail.
- Change the appearance of this organization to "Public" from the people list [here](https://github.com/orgs/SidHacksCommunity/people/).
- Join our Discord Server [here](https://discord.gg/gPyR9Q9n8M).
  - Accept the Rules from `#📓〡rules` channel.
  - Introduce yourself to our community in `👋〡introduction` channel.
- Feel free to share your excitement on socials with `#SidHacksCommunity`. You can also tag me `@siddharth_hacks`.

__Close this issue once you complete all the above points.__
- - -

Looking forward to interacting with you in our community! Welcome once again! 🤓

**Comment by Chanchal1603** [comment]
Yayyy, Done!
Thanks, Siddharth for such a warm welcome:D
