### ISSUE TITLE
Looking forward to get involved and contribute to the community 🎉

### ISSUE THREAD

**Issue by shuklaritvik06** [SidHacksCommunity/support#50]
### First Name

Ritvik

### Last Name

Shukla

### Discord Username (if applicable)

captain_jack#9750

### Let us understand your motive.

I have been a member of Programmers universal group on discord, I came to know about this from there and from twitter too, I love open source , contributed to layer5 orgs repo also (mainly in docs, as i am learning about the project more). I am skilled in C,C++,Python,Learning Java,basics of DSA i know!

**Comment by siddharthdayalwal** [comment]
![](https://media.giphy.com/media/LrY6OiICHS1TWZpGkf/giphy.gif)

Hey @shuklaritvik06 👋🏻 

Thanks for requesting an invite! Welcome to SidHacks Community 🎉 

Before going ahead, I would want you to complete the below To-Do list.

## Your To-Do List ✔️ 

- Accept the invitation sent to you via mail.
- Change the appearance of this organization to "Public" from the people list [here](https://github.com/orgs/SidHacksCommunity/people/).
- Join our Discord Server [here](https://discord.gg/gPyR9Q9n8M).
  - Accept the Rules from `#📓〡rules` channel.
  - Introduce yourself to our community in `👋〡introduction` channel.
- Feel free to share your excitement on socials with `#SidHacksCommunity`. You can also tag me `@siddharth_hacks`.

__Close this issue once you complete all the above points.__
- - -

Looking forward to interacting with you in our community! Welcome once again! 🤓
