### ISSUE TITLE
Looking forward to get involved and contribute to the community 🎉

### ISSUE THREAD

**Issue by Anurag30112003** [SidHacksCommunity/support#54]
### First Name

Anurag

### Last Name

Sharma

### Discord Username (if applicable)

Anurag#9801

### Let us understand your motive.

I want to join community help folks in projects  and also make awsome projects.

**Comment by siddharthdayalwal** [comment]
![](https://media.giphy.com/media/LrY6OiICHS1TWZpGkf/giphy.gif)

Hey @Anurag30112003 👋🏻 

Thanks for requesting an invite! Welcome to SidHacks Community 🎉 

Before going ahead, I would want you to complete the below To-Do list.

## Your To-Do List ✔️ 

- Accept the invitation sent to you via mail.
- Change the appearance of this organization to "Public" from the people list [here](https://github.com/orgs/SidHacksCommunity/people/).
- Join our Discord Server [here](https://discord.gg/gPyR9Q9n8M).
  - Accept the Rules from `#📓〡rules` channel.
  - Introduce yourself to our community in `👋〡introduction` channel.
- Feel free to share your excitement on socials with `#SidHacksCommunity`. You can also tag me `@siddharth_hacks`.

__Close this issue once you complete all the above points.__
- - -

Looking forward to interacting with you in our community! Welcome once again! 🤓
