### ISSUE TITLE
Looking forward to get involved and contribute to the community 🎉

### ISSUE THREAD

**Issue by aniruddhabagal** [SidHacksCommunity/support#57]
### First Name

Aniruddha

### Last Name

Bagal

### Discord Username (if applicable)

AlphaZGod#3498

### Let us understand your motive.

Hoping to contribute to this community and reach more number of people through this initiative!
Let's grow it together!🤩🙌🏻

**Comment by siddharthdayalwal** [comment]
Hey @aniruddhabagal you have already raise one issue over here: https://github.com/SidHacksCommunity/support/issues/52

Closing this issue! :)
