### ISSUE TITLE
Looking forward to get involved and contribute to the community 🎉

### ISSUE THREAD

**Issue by sakshamgurbhele** [SidHacksCommunity/support#68]
### First Name

SAKSHAM

### Last Name

GURBHELE

### Discord Username (if applicable)

SA KSH AM#0111

### Let us understand your motive.

I came to know about SidHack Community from Sidharth's Twitter handle. and I want to join this community because I want to contribute to open-source more and get exposure and meet new people with whom I can learn and grow. I know Java, HTML, CSS, and GCP. I am currently learning Android Development. I can help the people in the community and if they have any doubts, I can get their doubts to resolve.

**Comment by siddharthdayalwal** [comment]
![](https://media.giphy.com/media/LrY6OiICHS1TWZpGkf/giphy.gif)

Hey @sakshamgurbhele 👋🏻 

Thanks for requesting an invite! Welcome to SidHacks Community 🎉 

Before going ahead, I would want you to complete the below To-Do list.

## Your To-Do List ✔️ 

- Accept the invitation sent to you via mail.
- Change the appearance of this organization to "Public" from the people list [here](https://github.com/orgs/SidHacksCommunity/people/).
- Join our Discord Server [here](https://discord.gg/gPyR9Q9n8M).
  - Accept the Rules from `#📓〡rules` channel.
  - Introduce yourself to our community in `👋〡introduction` channel.
- Feel free to share your excitement on socials with `#SidHacksCommunity`. You can also tag me `@siddharth_hacks`.

__Close this issue once you complete all the above points.__
- - -

Looking forward to interacting with you in our community! Welcome once again! 🤓
