### ISSUE TITLE
Looking forward to contribute to community!!

### ISSUE THREAD

**Issue by yashwanth0203** [SidHacksCommunity/support#7]

**Comment by siddharthdayalwal** [comment]
Hey @yashwanth0203 

I would want you to raise an issue [here](https://github.com/SidHacksCommunity/support/issues/new?assignees=siddharthdayalwal&labels=invitation&template=invitation.yml&title=Looking+forward+to+get+involved+and+contribute+to+the+community+%F0%9F%8E%89).
