### ISSUE TITLE
Looking forward to get involved and contribute to the community 🎉

### ISSUE THREAD

**Issue by vaibhavgupta2499** [SidHacksCommunity/support#81]
### First Name

Vaibhav

### Last Name

Gupta

### Discord Username (if applicable)

vaibhavgupta#5585

### Let us understand your motive.

I am a fourth year engineering student, from Delhi, active in the field of Machine Learning and Data Science. I want to take part in hackathons related to these fields, therefore I plan to join this community. Here please refer to my LinkedIn profile to connect to me - https://www.linkedin.com/in/vaibhav-gupta-98b5671b0/

**Comment by siddharthdayalwal** [comment]
![](https://media.giphy.com/media/LrY6OiICHS1TWZpGkf/giphy.gif)

Hey @vaibhavgupta2499 👋🏻 

Thanks for requesting an invite! Welcome to SidHacks Community 🎉 

Before going ahead, I would want you to complete the below To-Do list.

## Your To-Do List ✔️ 

- Accept the invitation sent to you via mail.
- Change the appearance of this organization to "Public" from the people list [here](https://github.com/orgs/SidHacksCommunity/people/).
- Join our Discord Server [here](https://discord.gg/gPyR9Q9n8M).
  - Accept the Rules from `#📓〡rules` channel.
  - Introduce yourself to our community in `👋〡introduction` channel.
- Feel free to share your excitement on socials with `#SidHacksCommunity`. You can also tag me `@siddharth_hacks`.

__Close this issue once you complete all the above points.__
- - -

Looking forward to interacting with you in our community! Welcome once again! 🤓
